"""add inventory system with item ids

Revision ID: 081eab7665ae
Revises: 96d5c17a9046
Create Date: 2026-08-14 00:32:21.920155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081eab7665ae'
down_revision: Union[str, None] = '96d5c17a9046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_definitions',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('localization_key', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('stackable', sa.Boolean(), nullable=False),
    sa.Column('max_stack', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('localization_key')
    )
    op.create_index(op.f('ix_item_definitions_code'), 'item_definitions', ['code'], unique=True)
    op.create_table('inventory_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['item_id'], ['item_definitions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'item_id', name='uq_inventory_player_item')
    )
    op.create_index(op.f('ix_inventory_items_item_id'), 'inventory_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_player_id'), 'inventory_items', ['player_id'], unique=False)
    op.add_column('players', sa.Column('starter_pack_granted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'starter_pack_granted')
    op.drop_index(op.f('ix_inventory_items_player_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_item_definitions_code'), table_name='item_definitions')
    op.drop_table('item_definitions')
    # ### end Alembic commands ###
